In [12]:
import numpy as np

Define function that will return sin(x)

In [13]:
def sincalc(x):
    return (np.sin(x))

In [14]:
def coscalc(x):
    return (np.cos(x))

b is a created array with a thousand entries between 0 and 2pi.
<br>c is a copy of array b that has been updated to now be sin(b)
<br>d is a copy of array b that has been updated to now be cos(b)
<br>z is arrays b,c, and d all placed together and stacked, so it is one element per array per row.

In [15]:
b=np.linspace(0,2*np.pi, 100)

c = np.array(sincalc(b))

d=np.array(coscalc(b))

z=np.stack((b,c,d), axis=1)

Now print out the first 10 rows of array z, using a for loop.

In [16]:
for j in range(0,10):
    print(z[j, :])
    

[0. 0. 1.]
[0.06346652 0.06342392 0.99798668]
[0.12693304 0.12659245 0.99195481]
[0.19039955 0.18925124 0.9819287 ]
[0.25386607 0.25114799 0.9679487 ]
[0.31733259 0.31203345 0.95007112]
[0.38079911 0.37166246 0.92836793]
[0.44426563 0.42979491 0.90292654]
[0.50773215 0.48619674 0.87384938]
[0.57119866 0.54064082 0.84125353]
